### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by The-Daishogun** [alimaktabi/quera-frontend-task#2]
When building the project I encountered the following issues:

```
yarn build
info  - Loaded env from /tmp/quera-frontend-task/.env
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin

./pages/[username]/index.tsx
27:15  Warning: Do not use `<img>` element. Use `<Image />` from `next/image` instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./pages/[username]/repositories/index.tsx
23:17  Warning: Do not use `<img>` element. Use `<Image />` from `next/image` instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./pages/index.tsx
31:5  Warning: React Hook useCallback has missing dependencies: 'router' and 'setError'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types .Failed to compile.

./components/Button/index.tsx:2:48
Type error: Could not find a declaration file for module 'react-transition-group'. '/tmp/quera-frontend-task/node_modules/react-transition-group/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-transition-group` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-transition-group';`

  1 | import React, { Fragment, ReactNode, useEffect, useRef, useState } from "react"
> 2 | import { CSSTransition, TransitionGroup } from "react-transition-group"
    |                                                ^
  3 | import Styles from "./button.module.sass"
  4 | import Loading from "../Loading"
  5 | 

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/tmp/quera-frontend-task/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/tmp/quera-frontend-task/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
info  - Linting and checking validity of types .%
```

**Comment by Bob-six** [comment]
its my mistake of not putting react-transition-group types into package.json
It should be fixed now

**Comment by The-Daishogun** [comment]
Thanks for the fix
